### ISSUE TITLE
Layout broken on IE 11

### ISSUE THREAD

**Issue by ck2000** [BlackrockDigital/startbootstrap-creative#103]
![grafik](https://user-images.githubusercontent.com/3198123/37372273-72f48cd4-2712-11e8-865c-b9e3206a84cd.png)

**Comment by ck2000** [comment]
Anybody able to help me out with this?

**Comment by Flohyr** [comment]
Ok, 

the problem is in the render engine of IE11. For some reason it seems not to work out proper to calculate the 'my-auto' class in the index.html on line 60 which sets margin at the x and y axis to zero.

Anyhow - a workaround that fits for me is this: search for **./css/creative.css**. 
Go to **line 203** (class  _header.masthead_). 

Change the line from:
   `padding-top: 0`
to
  `padding-top: 95px;`

Regards,
Flohyr

**Comment by davidtmiller** [comment]
This is a workaround for sure, but the root cause of this is IE 11 and it not fully supporting flexbox.

**Comment by ck2000** [comment]
So no fix for IE11?
