### ISSUE TITLE
Change node modules to bower modules

### ISSUE THREAD

**Issue by kamronbatman** [BlackrockDigital/startbootstrap-creative#53]
Would be nice to change from using node modules to bower modules.

**Comment by davidtmiller** [comment]
A lot of folks are dropping Bower in favor of npm, and I'm doing the same with Start Bootstrap templates and themes. A major reason is to remove a task from setting up a development environment. If Bower were used, someone would need to run `npm install` and then `bower install` and then run the `gulp` task. With npm being used as the package manager for external libraries instead of Bower, you only need to run `npm install` and then `gulp` to set up the development environment.

There are many other reasons apart from the one above, but that's enough justification to just go with npm for the open source projects on Start Bootstrap.
